/* Basic cart + map quote (checkout happens on checkout.html) */
const CART_KEY='zyn_cart_v1';
const cartBtn=document.getElementById('cart-btn');
const drawer=document.getElementById('cart-drawer');
const closeCart=document.getElementById('close-cart');
const overlay=document.getElementById('cart-overlay');
const cartItemsEl=document.getElementById('cart-items');
const cartTotalEl=document.getElementById('cart-total');
const cartCountEl=document.getElementById('cart-count');

function getCart(){return JSON.parse(localStorage.getItem(CART_KEY)||'[]');}
function saveCart(c){localStorage.setItem(CART_KEY,JSON.stringify(c));renderCart();}
function renderCart(){const cart=getCart();cartItemsEl.innerHTML='';let t=0;cart.forEach((i,idx)=>{t+=i.price*i.qty;const row=document.createElement('div');row.className='cart-row';row.innerHTML=`<div><strong>${i.name}</strong> <small>(${i.flavor})</small></div><div>x ${i.qty} — $${(i.price*i.qty).toFixed(2)}</div>`;cartItemsEl.appendChild(row);});cartTotalEl.textContent=t.toFixed(2);cartCountEl.textContent=getCart().reduce((a,b)=>a+b.qty,0);}
document.addEventListener('click',(e)=>{if(e.target.classList.contains('add')){const b=e.target;const sku=b.dataset.sku;const name=b.dataset.name;const price=parseFloat(b.dataset.price);const flavor=document.querySelector(`select.flavor[data-sku="${sku}"]`).value;const qty=parseInt(document.querySelector(`input.qty[data-sku="${sku}"]`).value,10)||1;const cart=getCart();const idx=cart.findIndex(i=>i.sku===sku&&i.flavor===flavor);if(idx>=0)cart[idx].qty+=qty;else cart.push({sku,name,price,flavor,qty});saveCart(cart);openCart();}if(e.target.classList.contains('qty-btn')){const cart=getCart();const i=parseInt(e.target.dataset.idx,10);if(e.target.dataset.action==='inc')cart[i].qty++;if(e.target.dataset.action==='dec')cart[i].qty=Math.max(1,cart[i].qty-1);if(e.target.dataset.action==='rm')cart.splice(i,1);saveCart(cart);}});
function openCart(){drawer.classList.add('open');drawer.classList.remove('hidden');overlay.classList.add('open');overlay.classList.remove('hidden');}
function closeCartFn(){drawer.classList.remove('open');overlay.classList.remove('open');setTimeout(()=>{drawer.classList.add('hidden');overlay.classList.add('hidden');},180);}
cartBtn?.addEventListener('click',openCart);closeCart?.addEventListener('click',closeCartFn);overlay?.addEventListener('click',closeCartFn);
const ageGate=document.getElementById('age-gate');document.getElementById('age-yes')?.addEventListener('click',()=>{sessionStorage.setItem('age_ok','1');ageGate.classList.add('hidden');});document.getElementById('age-no')?.addEventListener('click',()=>{window.location.href='https://www.fda.gov/tobacco-products';});if(sessionStorage.getItem('age_ok')!=='1')ageGate.classList.remove('hidden');

const addrInput=document.getElementById('addr');const acList=document.getElementById('addr-ac');const quoteBtn=document.getElementById('quote');const quoteStatus=document.getElementById('quote-status');const feeDeliveryEl=document.getElementById('fee-delivery');const feeGasEl=document.getElementById('fee-gas');const grandTotalEl=document.getElementById('grand-total');const routeMiEl=document.getElementById('route-mi');
let lMap,lRouter,shopLatLng=null,destLatLng=null,lastQuote=null;
function debounce(fn,ms=250){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),ms);};}
function getCartTotal(){return getCart().reduce((s,i)=>s+i.price*i.qty,0);}
function initMap(){const fb={lat:39.7597,lng:-76.6760};lMap=L.map('map').setView([fb.lat,fb.lng],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(lMap);const provider=L.Control.Geocoder.nominatim();const shop=window.SHOP_ADDRESS||'30 South Main St, Railroad, PA 17355';provider.geocode(shop,(r)=>{const c=r?.[0]?.center||fb;shopLatLng={lat:c.lat,lng:c.lng};L.marker([c.lat,c.lng],{title:'Shop'}).addTo(lMap);lMap.setView([c.lat,c.lng],13);});const gc=L.Control.geocoder({defaultMarkGeocode:false}).addTo(lMap);gc.on('markgeocode',e=>chooseAddr({label:e.geocode.name,lat:e.geocode.center.lat,lon:e.geocode.center.lng}));lMap.on('click',e=>chooseAddr({label:`${e.latlng.lat.toFixed(5)}, ${e.latlng.lng.toFixed(5)}`,lat:e.latlng.lat,lon:e.latlng.lng}));}
function drawRoute(){if(!shopLatLng||!destLatLng)return;if(lRouter){lMap.removeControl(lRouter);lRouter=null;}lRouter=L.Routing.control({waypoints:[L.latLng(shopLatLng.lat,shopLatLng.lng),L.latLng(destLatLng.lat,destLatLng.lng)],router:L.Routing.osrmv1({serviceUrl:'https://router.project-osrm.org/route/v1'}),addWaypoints:false,draggableWaypoints:false,show:false,fitSelectedRoutes:true}).on('routesfound',e=>{routeMiEl.textContent=(e.routes[0].summary.totalDistance/1609.344).toFixed(2);}).addTo(lMap);}
const fetchSug=debounce(async(q)=>{if(!q||q.length<2){acList.innerHTML='';acList.classList.add('hidden');return;}const bb=shopLatLng?`${shopLatLng.lng-1},${shopLatLng.lat-1},${shopLatLng.lng+1},${shopLatLng.lat+1}`:'';const url=`https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&limit=8&countrycodes=us${bb?`&viewbox=${bb}&bounded=1`:''}&q=${encodeURIComponent(q)}`;try{const r=await fetch(url,{headers:{'User-Agent':'murica1stnicotine/1.0 (contact: merchant@example.com)'}});const j=await r.json();acList.innerHTML=j.map(d=>`<div class="ac-item" data-lat="${d.lat}" data-lon="${d.lon}">${d.display_name}</div>`).join('');acList.classList.remove('hidden');}catch{acList.innerHTML='';acList.classList.add('hidden');}},250);
function chooseAddr({label,lat,lon}){addrInput.value=label;destLatLng={lat,lng:lon};L.marker([lat,lon]).addTo(lMap);drawRoute();acList.innerHTML='';acList.classList.add('hidden');quoteStatus.textContent='Click "Get delivery quote" to compute fees.';}
addrInput?.addEventListener('input',e=>fetchSug(e.target.value));
document.addEventListener('click',e=>{if(e.target.classList.contains('ac-item')){chooseAddr({label:e.target.textContent,lat:parseFloat(e.target.dataset.lat),lon:parseFloat(e.target.dataset.lon)});}else if(!document.querySelector('.ac-wrap')?.contains(e.target)){acList.classList.add('hidden');}});
quoteBtn?.addEventListener('click',async()=>{const address=(addrInput?.value||'').trim();if(!address&&!destLatLng)return alert('Enter or pick a delivery address.');quoteStatus.textContent='Calculating…';try{const res=await fetch(`${window.API_BASE}/api/quote`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address,lat:destLatLng?.lat,lng:destLatLng?.lng})});const data=await res.json();document.getElementById('fee-delivery').textContent=data.fees.delivery.toFixed(2);document.getElementById('fee-gas').textContent=data.fees.gas.toFixed(2);document.getElementById('grand-total').textContent=(getCartTotal()+data.fees.delivery+data.fees.gas).toFixed(2);quoteStatus.textContent='Quote updated.';}catch{quoteStatus.textContent='Could not calculate.';}});

document.addEventListener('DOMContentLoaded',initMap);renderCart();
